version: "3.9"
services:
  api:
    build: ./backend
    container_name: deepfake_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEEPFAKE_DB=/data/deepfake_results.sqlite
      - DF_SAVE_PAYLOADS=1
      - DETECT_API_KEY=
      - DF_WEBHOOK_URL=
    restart: unless-stopped
    volumes:
      - deepfake_data:/data
  ui:
    image: streamlit/streamlit:1.37.0
    container_name: deepfake_ui
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
    command: bash -lc "pip install requests && streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0"

volumes:
  deepfake_data:

